### ISSUE TITLE
How can I pass the uploaded images to my server?

### ISSUE THREAD

**Issue by santhi-nyros** [baaraak/react-images-upload#5]
Really thank you soo much, you saved my time alot.

I need to save the uploaded image to my server, when I try to pass pictures state , I have getting 
Uncaught TypeError: Illegal invocation error.

Any help please..

**Comment by Tsvetkovv** [comment]
@santhi-nyros how did you solve the problem?

**Comment by santhi-nyros** [comment]
Yeah, I have solved it by converting pictures into  base64 files and then send to server.
